notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install -r docs/requirements.txt
  - pip install pylint
  - pip install coveralls
  - pip install .
script:
  - cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../setup.py && make html && cd ..
  - pylint circuitry
  - nosetests
after_success:
  - coveralls
